//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LukieAnnLoansAndFinancialServicesApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class loanIssueance
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public loanIssueance()
        {
            this.Repayments = new HashSet<Repayment>();
        }
    
        public int Id { get; set; }
        public Nullable<int> LoanRequest_Id { get; set; }
        public Nullable<decimal> LoanAmount { get; set; }
        public Nullable<decimal> MonthlyPayment { get; set; }
        public Nullable<decimal> Total { get; set; }
        public string status { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
    
        public virtual LoanRequest_Linker LoanRequest_Linker { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Repayment> Repayments { get; set; }
    }
}
