//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LukieAnnLoansAndFinancialServicesApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class LoanRequest_Linker
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LoanRequest_Linker()
        {
            this.loanIssueances = new HashSet<loanIssueance>();
        }
    
        public int Id { get; set; }
        public Nullable<int> Customer_Id { get; set; }
        public Nullable<int> LoanType_Id { get; set; }
        public Nullable<int> LoanTerm_Id { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<loanIssueance> loanIssueances { get; set; }
        public virtual Personnel_Table Personnel_Table { get; set; }
        public virtual LoanTerm LoanTerm { get; set; }
        public virtual LoanType LoanType { get; set; }
    }
}
