//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LukieAnnLoansAndFinancialServicesApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Login_DateTimeTable
    {
        public int Id { get; set; }
        public Nullable<int> Login_ID { get; set; }
        public Nullable<System.DateTime> Login_DateTime { get; set; }
        public Nullable<System.DateTime> Logout_DateTime { get; set; }
    
        public virtual personnel_LogIn personnel_LogIn { get; set; }
    }
}
