//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LukieAnnLoansAndFinancialServicesApp
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class LukieAnnsLoans_dbEntities : DbContext
    {
        public LukieAnnsLoans_dbEntities()
            : base("name=LukieAnnsLoans_dbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<LoanInterest> LoanInterests { get; set; }
        public virtual DbSet<loanIssueance> loanIssueances { get; set; }
        public virtual DbSet<LoanRequest_Linker> LoanRequest_Linker { get; set; }
        public virtual DbSet<LoanTerm> LoanTerms { get; set; }
        public virtual DbSet<LoanType> LoanTypes { get; set; }
        public virtual DbSet<Login_DateTimeTable> Login_DateTimeTable { get; set; }
        public virtual DbSet<personnel_LogIn> personnel_LogIn { get; set; }
        public virtual DbSet<Personnel_Login_LinkerTable> Personnel_Login_LinkerTable { get; set; }
        public virtual DbSet<Personnel_Table> Personnel_Table { get; set; }
        public virtual DbSet<PersonnelRoleTable> PersonnelRoleTables { get; set; }
        public virtual DbSet<Repayment> Repayments { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
    }
}
