//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LukieAnnLoansAndFinancialServicesApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Personnel_Login_LinkerTable
    {
        public int id { get; set; }
        public Nullable<int> personnel_Role_ID { get; set; }
        public Nullable<int> Personnel_ID { get; set; }
    
        public virtual PersonnelRoleTable PersonnelRoleTable { get; set; }
        public virtual Personnel_Table Personnel_Table { get; set; }
    }
}
